version: '2'
services:
  redis1:
    image: redis:5.0.6
    container_name: redis1
    command: redis-server /etc/redis/redis.conf
    ports:
#      - target: 6379
#        published: 20001
#        protocol: tcp
#        mode: host
      - "20001:6739/tcp"
    privileged: true
    volumes:
      - ./redis1/conf/redis.conf:/etc/redis/redis.conf
      - ./redis1/data:/data
    network_mode: "host"

  redis2:
    image: redis:5.0.6
    container_name: redis2
    command: redis-server /etc/redis/redis.conf
    ports:
#      - target: 6379
#        published: 20002
#        protocol: tcp
#        mode: host
      - "20002:6739/tcp"
    privileged: true
    volumes:
      - ./redis2/conf/redis.conf:/etc/redis/redis.conf
      - ./redis2/data:/data
    depends_on:
      - redis1
    network_mode: "host"
